zurnatikl/apps/journals/urls.py
from django.conf.urls import url
from zurnatikl.apps.journals import views


urlpatterns = [
    url(r'^$', views.JournalList.as_view(), name='list'),
    url(r'^items/$', views.SearchView.as_view(), name='search'),
    # journal contributor network urls
    url(r'^network/$', views.ContributorNetwork.as_view(), name='contributor-network'),
    url(r'^network.json$', views.ContributorNetworkJSON.as_view(), name='contributor-network-json'),
    url(r'^contributors.(?P<fmt>graphml|gml)$', views.ContributorNetworkExport.as_view(),
        name='contributor-network-export'),
    # greedier matching url patterns must come last
    url(r'^(?P<slug>[\w-]+)/$', views.JournalDetail.as_view(), name='journal'),
    url(r'^(?P<journal_slug>[\w-]+)/(?P<id>\d+)/$', views.IssueDetail.as_view(), name='issue'),
    url(r'^data/issues.csv$', views.JournalIssuesCSV.as_view(),
        name='csv-issues'),
    url(r'^data/items.csv$', views.JournalItemsCSV.as_view(), name='csv-items')

]

zurnatikl/apps/network/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from zurnatikl.apps.network import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="network/index.html"),
        name='index'),

    url(r'^data.(?P<fmt>gml|graphml)$', views.FullNetworkExport.as_view(),
        name='data'),
    # network graphs based on "schools"
    url(r'^schools/(?P<slug>[\w-]+)/$', views.SchoolsNetwork.as_view(),
        name='schools'),
    url(r'^schools/(?P<slug>[\w-]+).json$', views.SchoolsNetworkJSON.as_view(),
        name='schools-json'),
    url(r'^schools/(?P<slug>[\w-]+).(?P<fmt>gml|graphml)$',
        views.SchoolsNetworkExport.as_view(), name='schools-export'),
]

zurnatikl/apps/people/urls.py
from django.conf.urls import url
from .views import PeopleList, PersonDetail, Egograph, \
   EgographJSON, EgographExport, PeopleCSV

urlpatterns = [
    url(r'^$', PeopleList.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', PersonDetail.as_view(), name='person'),
    url(r'^(?P<slug>[\w-]+)/egograph/$', Egograph.as_view(),
        name='egograph'),
    url(r'^(?P<slug>[\w-]+)/egograph.json$', EgographJSON.as_view(),
        name='egograph-json'),
    url(r'^(?P<slug>[\w-]+)/egograph.(?P<fmt>graphml|gml)$', EgographExport.as_view(),
        name='egograph-export'),
    url(r'^data/people.csv$', PeopleCSV.as_view(), name='csv'),
]

zurnatikl/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from ajax_select import urls as ajax_select_urls


admin.autodiscover()


urlpatterns = [
    url(r'^', include('zurnatikl.apps.content.urls')),
    # TODO: eventually, move about/credit page templates into content
    url(r'^about/$', TemplateView.as_view(template_name="about.html"),
        name='about'),
    url(r'^credits/$', TemplateView.as_view(template_name="credits.html"),
        name='credits'),
    url(r'^legal/$', TemplateView.as_view(template_name="legal.html"),
        name='legal'),
    url(r'^network/', include('zurnatikl.apps.network.urls',
        namespace='network')),
    url(r'^journals/', include('zurnatikl.apps.journals.urls',
        namespace='journals')),
    url(r'^people/', include('zurnatikl.apps.people.urls',
        namespace='people')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls) ),

    # add redirect for favicon at root of site
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zurnatikl/apps/network/models.py
from django.db import models

# Create your models here.

danowski/apps/networks/forms.py
from django import forms
from danowski.apps.networks.models import Person, Journal, Issue, IssueItem, School

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person

        widgets = {
            'dwelling': forms.SelectMultiple(attrs={'style': "width:482px",
                                                    'width' : '482px'}),
            'schools': forms.SelectMultiple(attrs={'style': "width:482px",
                                                    'width' : '482px'})
        }

class JournalForm(forms.ModelForm):
    class Meta:
        model = Journal

        widgets = {
            'schools': forms.SelectMultiple(attrs={'style': "width:482px",
                                                    'width' : '482px'})
        }


class IssueForm(forms.ModelForm):
    class Meta:
        model = Issue

        widgets = {
            'print_address': forms.Select(attrs={'style': "width:482px",
                                                    'width' : '482px'}),
            'mailing_addresses': forms.SelectMultiple(attrs={'style': "width:482px",
                                                    'width' : '482px'}),
            'publication_address': forms.Select(attrs={'style': "width:482px",
                                                    'width' : '482px'})
        }


class IssueItemForm(forms.ModelForm):
    class Meta:
        model = IssueItem

        widgets = {
            'addresses': forms.SelectMultiple(attrs={'style': "width:482px",
                                                    'width' : '482px'}),
        }

class SchoolForm(forms.ModelForm):
    class Meta:
        model = School

        widgets = {
            'location': forms.Select(attrs={'style': "width:482px",
                                                    'width' : '482px'}),
        }

zurnatikl/apps/network/views.py
from collections import defaultdict
import itertools
import logging
import time

from django.views.generic import ListView
from igraph import Graph

from zurnatikl.apps.geo.models import Location
from zurnatikl.apps.journals.models import Journal, Issue, Item
from zurnatikl.apps.people.models import Person, School
from .utils import to_ascii, encode_unicode
from .base_views import NetworkGraphExportView, SigmajsJSONView


logger = logging.getLogger(__name__)


def generate_network_graph(use_ascii=False):
    '''Generate a :class:`networkx.MultiGraph` from the connections among
    schools, people, locations, journals, issues, and items.
    Optionally convert unicode to ascii, if needed by the export tool.
    '''
    start = time.time()
    # generate a graph for serialization
    # TODO: probably need to add caching on this graph
    graph = Graph()
    # igraph requires numerical id; zurnatikl uses network id to
    # differentiate content types & database ids

    # helper method to convert attributes to ascii or unicode as requested
    def attr(attributes):
        # force content to ascii if requested
        if use_ascii:
            return to_ascii(attributes)
        else:
            # explicitly encode unicode, as a workaround for
            # igraph/ascii errors
            # see https://github.com/igraph/python-igraph/issues/5
            return encode_unicode(attributes)

    schools = School.objects.all()
    edges = []
    for school in schools:
        graph.add_vertex(school.network_id,
                         **attr(school.network_attributes))
        # edges can't be added until both source and target nodes exist
        if school.has_network_edges:
            edges.extend(school.network_edges)

    people = Person.objects.all().prefetch_related('schools', 'dwellings')
    for person in people:
        graph.add_vertex(person.network_id,
                         **attr(person.network_attributes))
        if person.has_network_edges:
            edges.extend(person.network_edges)

    locations = Location.objects.all().prefetch_related('placename_set')
    for loc in locations:
        graph.add_vertex(loc.network_id,
                         **attr(loc.network_attributes))
        if loc.has_network_edges:
            edges.extend(loc.network_edges)

    journals = Journal.objects.all()
    for journal in journals:
        graph.add_vertex(journal.network_id,
                         **attr(journal.network_attributes))
        if journal.has_network_edges:
            edges.extend(journal.network_edges)

    issues = Issue.objects.all().prefetch_related('editors',
        'contributing_editors', 'publication_address', 'print_address',
        'mailing_addresses')
    for issue in issues:
        graph.add_vertex(issue.network_id,
                         **attr(issue.network_attributes))
        if issue.has_network_edges:
            edges.extend(issue.network_edges)
    items = Item.objects.all().prefetch_related('issue', 'creators',
        'translators', 'persons_mentioned', 'addresses', 'genre')
    for item in items:
        graph.add_vertex(item.network_id,
                         **attr(item.network_attributes))
        if item.has_network_edges:
            edges.extend(item.network_edges)

    # some edges have edge attributes, others do not
    # edges without attributes can be added en masse
    simple_edges = [edge for edge in edges if len(edge) == 2]
    graph.add_edges(simple_edges)
    edge_attrs = [edge for edge in edges if len(edge) > 2]
    for source, target, attributes in edge_attrs:
        graph.add_edge(source, target, **attributes)

    logger.debug('Generated full graph in %.2f sec' % (time.time() - start))
    return graph


class FullNetworkExport(NetworkGraphExportView):
    filename = 'network_data'

    def get_context_data(self, **kwargs):
        use_ascii = (self.export_format == 'gml')
        return generate_network_graph(use_ascii=use_ascii)


class SchoolsNetwork(ListView):
    model = School
    template_name = 'network/schools.html'

    def get_queryset(self):
        # url slug is for school categorizer
        return School.objects.filter(categorizer=self.kwargs['slug'])


class SchoolsNetworkBaseView(SchoolsNetwork):
    '''Base view for generating a network graph for a set of schools,
    for use in disseminating the graph as JSON, GEXF, or GraphML.'''

    def get_context_data(self, **kwargs):
        return School.schools_network(self.get_queryset())


class SchoolsNetworkJSON(SigmajsJSONView, SchoolsNetworkBaseView):
    '''Network graph based on a number of :class:`~zurnatikl.apps.people.models.School`
    objects in a JSON format appropriate for use with Sigma.js'''


class SchoolsNetworkExport(NetworkGraphExportView, SchoolsNetworkBaseView):
    '''Downloadable eggograph for a
    :class:`~zurnatikl.apps.people.models.School` group in GEXF or GraphML.'''

    def get_context_data(self, **kwargs):
        # set filename based on categorizer slug
        self.filename = '%s-schools' % kwargs['slug']
        # inherit graph generation logic
        return super(SchoolsNetworkExport, self).get_context_data(**kwargs)

zurnatikl/apps/network/templates/network/graph_base.html
{% extends 'site_base.html' %}
{% load static %}
{# base template for displaying a network graph #}
{# main blocks to extend: pregraph-content, postgraph-content, json-url or graph-init #}

{% block css %}
  {{ block.super }}
  <link href="{% static 'network/css/sigma.css' %}" rel="stylesheet"/>
  {# <link href="{% static 'css/cornermenu.css' %}" rel="stylesheet"/> #}
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{% static 'js/sigma/sigma.min.js' %}"></script>
    <script src="{% static 'js/sigma/plugins/sigma.parsers.json.min.js' %}"></script>
    <script src="{% static 'js/sigma/plugins/sigma.plugins.design.min.js' %}"></script>
    <script src="{% static 'js/sigma/plugins/sigma.renderers.edgeLabels.min.js' %}"></script>
    <script src="{% static 'js/sigma/plugins/sigma.renderers.customEdgeShapes.min.js' %}"></script>
    <script src="{% static 'js/sigma/plugins/sigma.renderers.parallelEdges.min.js' %}"></script>
    <script src="{% static 'js/sigma/plugins/sigma.plugins.fullScreen.min.js' %}"></script>
    <script src="{% static 'network/js/initgraph.js' %}"></script>
    {% block graph-init %} {# extend to override config options #}
    <script>
    var s = init_sigma_graph({json_url: "{% block json-url %}{% endblock %}"});

    </script>
    {% endblock %}
{% endblock %}

{% block content %}
<section class="row">
    <div class="col-sm-12">
        <div class="content">

{% block pregraph-content %}{% endblock %}

<div id="sigma-container">
  <div id="graph-container">
      <div id="graph-status">
      <span class="status">
        <span id="text">Loading</span>... <i class="fa fa-spinner fa-spin"></i>
      </span>
      </div>


  {# graph control panel #}
  <div class="filter-container">
      {# download menu #}
      {% block download-graph %}{% endblock %}
      {# button to make graph fullscreen  #}
      <div>
          <a class="btn btn-secondary" id="graph-fullscreen" title="View Graph in Full Screen"><span class="fa fa-arrows-alt"></span></a>
      </div>
      {# control panel / key #}
      <div>
          <a class="btn btn-default settings-btn menu-button"><span class="fa fa-cogs"></span><span class="caret"></span></a>
          <div id="graphMenu" class='settings-menu'>
              <nav class="menu">
                  {% block graph-controls %}{% endblock %}
                  <div id="graph-color-key">
                      <h4>Color Guide</h4>
                      {# all graphs will have the option of showing color key for node/type #}
                      <div id="graph-type-colors" class="color-key">
                        <div id="type">
                            <h5>Nodes</h5>
                            <dl class="graph-colors" id="node-colors"></dl>
                               {% comment %} actual colors will be added by graph init in this format
                              <dt style="background-color:#004052"/>
                              <dd>Person</dd> {% endcomment %}
                            <h5>Edges</h5>
                            <dl class="graph-colors" id="edge-colors"></dl>
                        </div>
                      </div>
                      {% block graph-color-keys %}{% endblock %}
                  </div>
              </nav>
          </div>
      </div>

  </div>
  </div>
</div>

{# control panel for graph interaction #}
{# NOTE: putting this inside the graph-container div makes it available in fullscreen #}
{# but probably need additional/different style/position for fullscreen #}
{% comment %}
<div class="menu-wrap">
        <nav class="menu">
         {# allow extending template to add controls #}

        {% block graph-controls %}{% endblock %}
         <div id="graph-color-key">
           <h4>Colors</h4>
             <div>
             <h5>Nodes</h5>
             <dl class="graph-colors" id="node-colors"></dl>
             {% comment %} actual colors will be added by graph init in this format
              <dt style="background-color:#004052"/>
              <dd>Person</dd>
               <h5>Edges</h5>
              <dl class="graph-colors" id="edge-colors"></dl>
          </dl>
        </div>
        </nav>
      </div>
      <button class="menu-button" id="open-button"><i class="fa fa-fw fa-cog"></i><span>Open Menu</span></button>
      <!-- <button clas="menu-button" id="open-filter-button"><i class="fa fa-fw fa-filter"></i><span>Open Filters</span></button> -->
      <button class="menu-button" id="graph-fullscreen" title="view fullscreen"><i class="fa fa-arrows-alt"></i> </button>
</div>
{% endcomment %}
{% block postgraph-content %}{% endblock %}


</div>
</div>
</section>
{% endblock %} {# content #}

zurnatikl/apps/network/templates/network/index.html
{% extends 'page_base.html' %}
{% load static %}

{% block page-subtitle %} | Networks{% endblock %}

{% block content-title %}Networks{% endblock %}

{% block breadcrumb-links %}
  <li class="active">Networks</li>
{% endblock %}

{% block page-content %}
<p>
  The network graphs here aim to illustrate literary communities. One graph is generated from Donald Allen's remarks about poetic schools in the introduction to <em>The New American Poetry, 1945-1960</em>. Allen associates people, places, and journals with certain schools of poetry: the New York School, the Beats, Black Mountain, and so on. The other network graph visualizes connections among <a href="https://testdanowski.library.emory.edu/nnap/people/">editors, authors, and translators</a> of <a href="https://testdanowski.library.emory.edu/nnap/journals/">twelve poetry journals</a> of the era. <em>Networking the New American Poetry</em> seeks to compare the schools Allen describes with the communities detected in the journals' data.
</p>

<div class="row">
  <div class="col-xs-8 col-sm-6 col-md-6">
    <a href="{% url 'network:schools' 'donald-allen' %}" class="thumbnail"
        title="Schooling Donald Allen network graph">
        <img src="{% static 'images/schools_graph.png' %}"
             alt="Thumbnail image of the Schooling Donald Allen network graph"/>
    </a>
  </div>
  <div class="col-xs-8 col-sm-6 col-md-6">
    <a href="{% url 'journals:contributor-network' %}" class="thumbnail"
       title="Journal contributor network graph">
        <img src="{% static 'images/journal_communities.png' %}"
        alt="Thumbnail image of the journals contribution network graph"/>
    </a>
  </div>
</div>
{# TODO: generate smaller images and use html5 picture element #}

<p>
  Network graphs are made up of nodes (the points) and edges (the lines that connect the nodes). In the journal contribution graph here, the nodes are journals or people, and the edges represent various relationships. The people are editors, authors, and/or translators with connections to the journals they contributed to, as well as connections to other people. These connections include those between co-editors, co-authors, editors and contributors, and translators and authors.
</p>

<p>
  The size of the nodes are determined by how many connections the node has. If two nodes are connected in multiple ways—for instance, if a person both edited and contributed to a journal—there will be multiple edges between those two nodes. As you zoom into the graph, you will be able to view the node labels. The colors indicate communities, as detected by an algorithm that takes into account the number of connections and the weight of connections. For example, the edge between co-authors will be more heavily weighted than the edge between an author and a journal. Each time you refresh the page, the graph will be laid out anew.
</p>

<p>
  On each <a href="{% url 'people:list' %}">people page</a>, you can view an egograph for that person, a subset of the full contributor graph. The egograph displays the person’s individual node, all of the one-degree connections to that node, and connections among those nodes. The egographs include edge labels.<sup><a href="#fn1" id="ref1">1</a></sup>
</p>

<h3>Observations</h3>
<p>
  The journal contributor graph draws on a much larger and much more complex dataset than that of Allen’s schools. While Allen himself remarked that his divisions “are somewhat arbitrary and cannot be taken as rigid categories,” the journal contributor graph underlines that lack of rigidity by providing a more accurate picture defined by who was contributing to and editing a set of journals. Of course, the goals of an anthologist and the goals of a social network analyst differ widely. Where Allen was trying to selectively curate poets and poems as a tastemaker—an arbiter of the best and brightest—we are trying to reconstruct the significant complexity of Allen’s publishing milieu.
</p>
<p>
  Our graphs represent textual relationships as social relationships because textual relationships originate in social bonds, require social interaction to facilitate production, and expand materially to produce textual communities through shared readership. While some members of our text community were activists and maintained significant public profiles (e.g. LeRoi Jones (Amiri Baraka) and Allen Ginsberg), others were more insular than public, more attuned to literary than public discourse (though of course the two aren’t mutually exclusive). Part of our work here is to give this text community a wider public and, in so doing, to encourage new perspectives on a history as yet half told.
</p>
<p>
  The shape of the communities that we see in the contributor graph suggests a network both less regimented and more capacious than Allen’s anthology indicates. In part, Allen has simply done the work of the anthologist, pruning and aggregating according to taste and other motivations. For us, the “other motivations” are ultimately most interesting and lead us to intriguing questions about the character of interactions and hierarchies within the interlinked textual communities. When we compare Allen’s categories to our graph, we can see that Allen’s poetic schools, which have come to define conversations about mid-century American poetry, were in practice quite permeable, as with the 5<sup>th</sup> Group and the Beats; and at times his groups are incoherent, as with the San Francisco Renaissance and the New York School.
</p>
<p>
  To put it another way, our graphs show empirically that Allen’s schools have led scholars to overlook significant sites of social and creative activity. For instance, Allen’s schools do not easily accommodate the significant textual communities that arose in the 1960s, after the anthology’s publication. These communities center on magazines and their editors, such as Beatitude (ed. John Kelly and Bob Kaufman), C: <em>A Journal of Poetry</em> (ed. Ted Berrigan), and <em>Intrepid</em> (ed. Allen de Loach).  More problematically, we can also observe at least one instance in which a text community that centers on a magazine (<em>Origin</em>) is associated with a school (Black Mountain) whereas the magazine’s editor (Cid Corman), who is also a prolific poet, is not associated with any school—a striking omission. A thoroughgoing look into the history of the period and the archives of these important community members could provide suggestive evidence which would allow scholars to redress the now-conspicuous critical silences that Allen’s anthology has perpetuated.
</p>

<h3>Conclusion</h3>
<p>
  Much more remains to be said about the ways in which our network helps to rethink the history of literary production in mid-century American poetry and beyond. Among many possibilities, we envision the following three topoi for further investigation:
</p>

<ul>
  <li>
    <strong>Shadow Canons</strong>: To what extent do the graphs suggests trajectories for American poetry that scholars have overlooked due to the influence of Allen’s narrative?
  </li>
  <li>
    <strong>Relative Influence</strong>: How might a dataset that includes mainstream anthologies (like the Norton) illuminate the relative influence of Allen’s anthology?
  </li>
  <li>
    <strong>Network Evolution</strong>: How did the network of avant garde poetry publishing evolve over time? Did the geographies shift in significant ways?
  </li>
</ul>

<p>
  Social network analysis provides one way to view historical periods and social groups with new eyes, and we invite scholars to engage with our data and visualizations to develop useful historical and interpretive models.<sup><a href="#fn2" id="ref2">2</a></sup>
</p>

<p>
  <em>This section was peer reviewed by Walter B. Kalaidjian, Department of English, Emory University.</em>
</p>
<hr></hr>

<p>
<sup id="fn1">
  1. To find out more about network graphs, David Easley and Jon Kleinberg's <a href="http://www.cs.cornell.edu/home/kleinber/networks-book/">Networks, Crowds, and Markets</a> and Manuel Lima's <a href="http://www.visualcomplexity.com/vc/about.cfm">Visual Complexity</a> offer good starting points. David Easley and Jon Kleinberg, <em>Networks, Crowds, and Markets: Reasoning about a Highly Connected World</em> (New York: Cambridge University Press, 2010); Manuel Lima, <em>Visual Complexity: Mapping Patterns of Information</em> (New York: Princeton Architectural Press, 2011).
  <a href="#ref1" title="Jump back to footnote 1 in the text.">↩</a>
</sup>
</p>

<p>
<sup id="fn2">
  2. For an excellent example of recent work in this vein, see Richard Jean So and Hoyt Long. "Network Analysis and the Sociology of Modernism." <em>boundary</em> 2 40, no. 2 (2013): 147-82.
  <a href="#ref2" title="Jump back to footnote 2 in the text.">↩</a>
</sup>
</p>


{% endblock %}

zurnatikl/apps/network/templates/network/schools.html
{% extends 'network/graph_base.html' %}
{% load static %}
{# display a network graph for people and places associated with a set of schools #}

{% block page-subtitle %} | Networks | Schools | {{ object_list.0.categorizer_name }}{% endblock %}

{% block breadcrumb-links %}
  <li>Schools</li>
  <li class="active">Categorized by {{ object_list.0.categorizer_name }}</li>
{% endblock %}

{% block download-graph %}
  {% with object_list.0.categorizer as slug %}
    {% url 'network:schools-export' slug 'graphml' as graphml_url %}
    {% url 'network:schools-export' slug 'gml' as gml_url %}
    {% include 'network/snippets/download_graph.html' %}
  {% endwith %}
{% endblock %}

{% block pregraph-content %}
<div class="container">


<h1>Schools categorized by {{ object_list.0.categorizer_name }}</h1>
<p>People, journals, and locations associated with schools as
    categorized by {{ object_list.0.categorizer_name }}.</p>
{# schools available in object_list if we want to list them #}
</div>
{% endblock %}

{% block graph-init %}
<script>
var s = init_sigma_graph({
  json_url: "{% url 'network:schools-json' object_list.0.categorizer %}",
  forceLink:  {
     autoStop: true,
     strongGravityMode: true,  {# this graph displays better with stronger gravity #}
     iterationsPerRender: 70,
  }
});

// schools graph edges do not have types, and are not really
// directional; set them all to a neutral (gray-green from network colors)
$('#graph-container').on('graph:design_applied', function() {
    s.graph.edges().forEach(function(edge) {
      edge.color = '#577469';
    });
});
</script>
{% endblock %}