zurnatikl/apps/content/urls.py
from django.conf.urls import patterns, url
from zurnatikl.apps.content import views
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', views.SiteIndex.as_view(), name='site-index'),
    url(r'^download/$', TemplateView.as_view(template_name="download.html"),
        name='download'),
]

zurnatikl/apps/journals/urls.py
from django.conf.urls import url
from zurnatikl.apps.journals import views


urlpatterns = [
    url(r'^$', views.JournalList.as_view(), name='list'),
    url(r'^items/$', views.SearchView.as_view(), name='search'),
    # journal contributor network urls
    url(r'^network/$', views.ContributorNetwork.as_view(), name='contributor-network'),
    url(r'^network.json$', views.ContributorNetworkJSON.as_view(), name='contributor-network-json'),
    url(r'^contributors.(?P<fmt>graphml|gml)$', views.ContributorNetworkExport.as_view(),
        name='contributor-network-export'),
    # greedier matching url patterns must come last
    url(r'^(?P<slug>[\w-]+)/$', views.JournalDetail.as_view(), name='journal'),
    url(r'^(?P<journal_slug>[\w-]+)/(?P<id>\d+)/$', views.IssueDetail.as_view(), name='issue'),
    url(r'^data/issues.csv$', views.JournalIssuesCSV.as_view(),
        name='csv-issues'),
    url(r'^data/items.csv$', views.JournalItemsCSV.as_view(), name='csv-items')

]

zurnatikl/apps/network/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from zurnatikl.apps.network import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="network/index.html"),
        name='index'),

    url(r'^data.(?P<fmt>gml|graphml)$', views.FullNetworkExport.as_view(),
        name='data'),
    # network graphs based on "schools"
    url(r'^schools/(?P<slug>[\w-]+)/$', views.SchoolsNetwork.as_view(),
        name='schools'),
    url(r'^schools/(?P<slug>[\w-]+).json$', views.SchoolsNetworkJSON.as_view(),
        name='schools-json'),
    url(r'^schools/(?P<slug>[\w-]+).(?P<fmt>gml|graphml)$',
        views.SchoolsNetworkExport.as_view(), name='schools-export'),
]

zurnatikl/apps/people/urls.py
from django.conf.urls import url
from .views import PeopleList, PersonDetail, Egograph, \
   EgographJSON, EgographExport, PeopleCSV

urlpatterns = [
    url(r'^$', PeopleList.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', PersonDetail.as_view(), name='person'),
    url(r'^(?P<slug>[\w-]+)/egograph/$', Egograph.as_view(),
        name='egograph'),
    url(r'^(?P<slug>[\w-]+)/egograph.json$', EgographJSON.as_view(),
        name='egograph-json'),
    url(r'^(?P<slug>[\w-]+)/egograph.(?P<fmt>graphml|gml)$', EgographExport.as_view(),
        name='egograph-export'),
    url(r'^data/people.csv$', PeopleCSV.as_view(), name='csv'),
]

zurnatikl/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from ajax_select import urls as ajax_select_urls


admin.autodiscover()


urlpatterns = [
    url(r'^', include('zurnatikl.apps.content.urls')),
    # TODO: eventually, move about/credit page templates into content
    url(r'^about/$', TemplateView.as_view(template_name="about.html"),
        name='about'),
    url(r'^credits/$', TemplateView.as_view(template_name="credits.html"),
        name='credits'),
    url(r'^legal/$', TemplateView.as_view(template_name="legal.html"),
        name='legal'),
    url(r'^network/', include('zurnatikl.apps.network.urls',
        namespace='network')),
    url(r'^journals/', include('zurnatikl.apps.journals.urls',
        namespace='journals')),
    url(r'^people/', include('zurnatikl.apps.people.urls',
        namespace='people')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls) ),

    # add redirect for favicon at root of site
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zurnatikl/apps/content/models.py
from django.db import models
from django.utils.safestring import mark_safe

from stdimage.models import StdImageField


class ImageQuerySet(models.QuerySet):
    def homepage_images(self):
        return self.filter(homepage=True)

    def banner_images(self):
        return self.filter(banner=True)

class ImageManager(models.Manager):
    def get_queryset(self):
        return ImageQuerySet(self.model, using=self._db)

    def homepage_images(self):
        return self.get_queryset().homepage_images()

    def banner_images(self):
        return self.get_queryset().banner_images()

class Image(models.Model):
    image = StdImageField(
        variations={
            # for convenience / display in admin
            'thumbnail': {'width': 50, 'height': 50, 'crop': True},
            # sizes needed for site design use
            'homepage': {'width': 479, 'height': 273, 'crop': True},
            'homepage_sm': {'width': 320, 'height': 176, 'crop': True},
            'banner': {'width': 479, 'height': 190, 'crop': True},
            'banner_sm': {'width': 320, 'height': 127, 'crop': True},
        })
    title = models.CharField(max_length=255)
    alt_text = models.CharField(max_length=255, blank=True)
    caption = models.TextField(blank=True)
    # future: rights/permissions statement?

    homepage = models.BooleanField(default=False,
        help_text='Use as a homepage image')
    banner = models.BooleanField(default=False,
        help_text='Use as a site banner image')

    objects = ImageManager()

    def __unicode__(self):
        return self.title

    def admin_thumbnail(self):
        return mark_safe('<img src="%s"/>' % self.image.thumbnail.url)

    admin_thumbnail.short_description = 'thumbnail'

zurnatikl/apps/content/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from .models import Image
from zurnatikl.apps.people.models import Person
from zurnatikl.apps.journals.models import Journal, Item, Issue, Genre



class SiteIndex(TemplateView):
    # TODO: move template under content app
    template_name = "site_index.html"

    def get_context_data(self):
        # select 5 random home page images
        images = list(Image.objects.homepage_images().order_by('?')[:4])
        # NOTE: using list to harden the selection to avoid getting a
        # different random set part way through, with possibility of repeating
        return {
            'images': images,
            # provide an alternate banner image to ensure we don't
            # get a repeat with an image on the homepage
            # (overrides the one set by context processor)
            'banner_image': Image.objects.banner_images() \
                                 .exclude(id__in=[img.id for img in images]) \
                                 .order_by('?').first()
        }

zurnatikl/apps/content/templates/download.html
{% extends 'page_base.html' %}

{% block page-subtitle %} | Download Data{% endblock %}

{% block content-title %}Download Data{% endblock %}

{% block breadcrumb-links %}
  <li class="active">Download the Data</li>
{% endblock %}

{% block page-content %}
  <p>
    The data presented here for download was entered into our databases by hand. Data points were collected from twelve journals of midcentury American poetry held by the Danowski Poetry Library as part of the Stuart A. Rose Manuscript, Archives, & Rare Book Library. Our data focus on bibliographic information about the publications (e.g. date and place of publication), but we also include some biographical information about the contributors (e.g. aliases, alternate names, and in some cases gender). In all, we entered over 10,000 pieces of data for 750 different authors, editors, and translators. The network graphs are built with <a href="https://github.com/emory-libraries-ecds/zurnatikl/">zurnatikl</a>, a Django web application developed by Emory software designers to investigate and analyze the networks among journal contributors such as authors, editors, and translators.
  </p>

  <h2>CSV Data</h2>
  <p>
      <ul>
          <li>
              <a href="{% url 'people:csv' %}">People</a>
          </li>
          <li>
              <a href="{% url 'journals:csv-issues' %}">Journal Issues</a>
          </li>
          <li>
              <a href="{% url 'journals:csv-items' %}">Journal Items</a>
          </li>

      </ul>
  </p>

  <h2>Network Graphs</h2>
  <p>
    <ul>
      <li>Schools categorized by Donald Allen:
        <a href="{% url 'network:schools-export' 'donald-allen' 'graphml' %}">GraphML</a> |
        <a href="{% url 'network:schools-export' 'donald-allen' 'gml' %}">GML</a>
        </li>
      <li>Journal contributor network:
        <a href="{% url 'journals:contributor-network-export' 'graphml' %}">GraphML</a> |
        <a href="{% url 'journals:contributor-network-export' 'gml' %}">GML</a>
      </li>
      <li>All journal data in network form:
        <a href="{% url 'network:data' 'graphml' %}">GraphML</a> |
        <a href="{% url 'network:data' 'gml' %}">GML</a>
      </li>
    </ul>
  </p>

<h2>Preferred Citation</h2>
<p>
  Raymond Danowski Poetry Library: Digital Danowski. <em>Networking the New American Poetry</em>. Emory University, 2016. https://danowski.library.emory.edu/nnap
</p>

<h2>Data Summary</h2>

<h3>Format</h3>

<p>
  Data are currently available as CSV files generated from the database, and as network graph files. The CSV files are based on the data collected for people, journal issues, and journal items. The files can be read relationally by cross-referencing people names against contributors listed as editors of journal issues or authors of journal items. For information about a journal issue in which an item (e.g. a poem) appears, cross-reference the journal items export with the journal issues data.
</p>

<p>
  The network graphs are generated by the zurnatikl software that runs the website, and are also the basis for the network visualizations displayed on the site.  There are three different network graphs available, which represent different and overlapping content.  The first file is a network graph representation of our interpretation of Donald Allen’s categorization of people, journals, and places associated with particular “schools” of poetry.  The second is the full journal contributor network that is displayed on the site and also used for individual contributor egographs. This network includes all journals and journal contributors (editors, authors, and translators).  The network relates editors, authors, and translators to the journals that they contributed to, and also tracks relationships for co-editors, co-authors, author/translator, and journal contributor and editor.  The strength of these connections are available as an edge weight based on the number or frequency of contribution or collaboration.  The third file is a full export of all journals, issues, and journal items, and journal contributors with all attributes in network form; this was an early export that was used for initial analysis and was the basis for early presentations on the projects, and is provided here for reference and in case it is useful.  The network graph files are available here in GraphML and GML format, both of which can be read by SNA software such as Gephi, Cytoscape, and the iGraph package for R. Additional historical and contextual information about the graphs can be found on the “About”  and “Networks” pages.
</p>


<h3>Data Quality</h3>

<p>
  Data were manually entered rather than extracted via OCR. Due to the way the data were collected, by numerous people over several months as the project developed, some fields remain incomplete or inconsistently filled out. In the people.csv, for example, the field for “Associated Schools” is incomplete because only select contributors were assigned to schools by Allen, while the field for “URI” was gathered inconsistently—an artifact of the project’s mid-stream course corrections as well as practical limitations. We have also chosen to include the notes field in which we jotted down comments as we collected the data.
</p>

<h3>Acknowledgements</h3>
<p>Data description was prepared by Rebecca Sutton Koeser and Bryan Chitwood.</p>

{% endblock %}