zurnatikl/apps/journals/urls.py
from django.conf.urls import url
from zurnatikl.apps.journals import views


urlpatterns = [
    url(r'^$', views.JournalList.as_view(), name='list'),
    url(r'^items/$', views.SearchView.as_view(), name='search'),
    # journal contributor network urls
    url(r'^network/$', views.ContributorNetwork.as_view(), name='contributor-network'),
    url(r'^network.json$', views.ContributorNetworkJSON.as_view(), name='contributor-network-json'),
    url(r'^contributors.(?P<fmt>graphml|gml)$', views.ContributorNetworkExport.as_view(),
        name='contributor-network-export'),
    # greedier matching url patterns must come last
    url(r'^(?P<slug>[\w-]+)/$', views.JournalDetail.as_view(), name='journal'),
    url(r'^(?P<journal_slug>[\w-]+)/(?P<id>\d+)/$', views.IssueDetail.as_view(), name='issue'),
    url(r'^data/issues.csv$', views.JournalIssuesCSV.as_view(),
        name='csv-issues'),
    url(r'^data/items.csv$', views.JournalItemsCSV.as_view(), name='csv-items')

]

zurnatikl/apps/network/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView
from zurnatikl.apps.network import views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="network/index.html"),
        name='index'),

    url(r'^data.(?P<fmt>gml|graphml)$', views.FullNetworkExport.as_view(),
        name='data'),
    # network graphs based on "schools"
    url(r'^schools/(?P<slug>[\w-]+)/$', views.SchoolsNetwork.as_view(),
        name='schools'),
    url(r'^schools/(?P<slug>[\w-]+).json$', views.SchoolsNetworkJSON.as_view(),
        name='schools-json'),
    url(r'^schools/(?P<slug>[\w-]+).(?P<fmt>gml|graphml)$',
        views.SchoolsNetworkExport.as_view(), name='schools-export'),
]

zurnatikl/apps/people/urls.py
from django.conf.urls import url
from .views import PeopleList, PersonDetail, Egograph, \
   EgographJSON, EgographExport, PeopleCSV

urlpatterns = [
    url(r'^$', PeopleList.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', PersonDetail.as_view(), name='person'),
    url(r'^(?P<slug>[\w-]+)/egograph/$', Egograph.as_view(),
        name='egograph'),
    url(r'^(?P<slug>[\w-]+)/egograph.json$', EgographJSON.as_view(),
        name='egograph-json'),
    url(r'^(?P<slug>[\w-]+)/egograph.(?P<fmt>graphml|gml)$', EgographExport.as_view(),
        name='egograph-export'),
    url(r'^data/people.csv$', PeopleCSV.as_view(), name='csv'),
]

zurnatikl/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from ajax_select import urls as ajax_select_urls


admin.autodiscover()


urlpatterns = [
    url(r'^', include('zurnatikl.apps.content.urls')),
    # TODO: eventually, move about/credit page templates into content
    url(r'^about/$', TemplateView.as_view(template_name="about.html"),
        name='about'),
    url(r'^credits/$', TemplateView.as_view(template_name="credits.html"),
        name='credits'),
    url(r'^legal/$', TemplateView.as_view(template_name="legal.html"),
        name='legal'),
    url(r'^network/', include('zurnatikl.apps.network.urls',
        namespace='network')),
    url(r'^journals/', include('zurnatikl.apps.journals.urls',
        namespace='journals')),
    url(r'^people/', include('zurnatikl.apps.people.urls',
        namespace='people')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls) ),

    # add redirect for favicon at root of site
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/nav-sidebar.html
{% load widget_tweaks %}
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
            <div class="input-group col-md-12">
           {% if search_form %}
            <form {# class="form-search navbar-search"#} role="form" method="GET" action="{% url 'journals:search' %}">
                <label class="sr-only" for="{{ search_form.keyword.name }}">{{ search_form.keyword.label }}</label>
                {% render_field search_form.keyword class+="search-query form-control" placeholder='Search' data-toggle="tooltip" data-placement="bottom" data-animation="true" autocomplete="off" data-original-title=search_form.keyword.help_text %}
                <span class="input-group-btn">
                    <button class="btn btn-danger" type="button">
                        <span class=" glyphicon glyphicon-search"></span>
                    </button>
                </span>
            </form>
           {% endif %} {# search form #}
           </div>
                <li class="sidebar-brand">
                    <a href="{% url 'site-index' %}">
                        Networking the <strong>New American Poetry</strong>
                    </a>
                </li>
                <ul>
                    <li>
                        <a href="{% url 'about' %}">Learn About the Project</a>
                    </li>
                    <li>
                        <a href="{% url 'journals:list' %}">Browse the Journals</a>
                    </li>
                    <li>
                        <a href="{% url 'people:list' %}">Journal Contributors</a>
                    </li>
                    <li>
                        <a href="{% url 'network:index' %}">View the Connections</a>
                    </li>
                    <li>
                        <a href="{% url 'download' %}">Download the Data</a>
                    </li>
                </ul>
            </ul>

            <div class="footer">
                <p><a href="http://it.emory.edu/" target="_blank" style="border-bottom: none;"> <img src="/static/images/emory_lits.svg" style="width: 50%; margin-bottom: 15px;"> </a> </p>
                <p>A <a href="https://danowski.digitalscholarship.emory.edu/">Digital Danowski</a> Initiative</p>
                <nav>
                    <ul>
                    <li><a href="{% url 'credits' %}">Credits</a></li>
                    <li><a href="{% url 'legal' %}">Legal</a></li>
                    {% if user.is_staff %} {# admin link for logged-in staff #}
                    <li>
                      <a href="{% url 'admin:index' %}" title="Admin">Admin{# <i class="fa fa-cog"></i>#}</a>
                    </li>
                    {% endif %}
                    </ul>
                </nav>
            </div>


        </div>
        <!-- /#sidebar-wrapper -->