zurnatikl/apps/journals/urls.py
from django.conf.urls import url
from zurnatikl.apps.journals import views


urlpatterns = [
    url(r'^$', views.JournalList.as_view(), name='list'),
    url(r'^items/$', views.SearchView.as_view(), name='search'),
    # journal contributor network urls
    url(r'^network/$', views.ContributorNetwork.as_view(), name='contributor-network'),
    url(r'^network.json$', views.ContributorNetworkJSON.as_view(), name='contributor-network-json'),
    url(r'^contributors.(?P<fmt>graphml|gml)$', views.ContributorNetworkExport.as_view(),
        name='contributor-network-export'),
    # greedier matching url patterns must come last
    url(r'^(?P<slug>[\w-]+)/$', views.JournalDetail.as_view(), name='journal'),
    url(r'^(?P<journal_slug>[\w-]+)/(?P<id>\d+)/$', views.IssueDetail.as_view(), name='issue'),
    url(r'^data/issues.csv$', views.JournalIssuesCSV.as_view(),
        name='csv-issues'),
    url(r'^data/items.csv$', views.JournalItemsCSV.as_view(), name='csv-items')

]

zurnatikl/apps/people/urls.py
from django.conf.urls import url
from .views import PeopleList, PersonDetail, Egograph, \
   EgographJSON, EgographExport, PeopleCSV

urlpatterns = [
    url(r'^$', PeopleList.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', PersonDetail.as_view(), name='person'),
    url(r'^(?P<slug>[\w-]+)/egograph/$', Egograph.as_view(),
        name='egograph'),
    url(r'^(?P<slug>[\w-]+)/egograph.json$', EgographJSON.as_view(),
        name='egograph-json'),
    url(r'^(?P<slug>[\w-]+)/egograph.(?P<fmt>graphml|gml)$', EgographExport.as_view(),
        name='egograph-export'),
    url(r'^data/people.csv$', PeopleCSV.as_view(), name='csv'),
]

zurnatikl/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView, RedirectView

from ajax_select import urls as ajax_select_urls


admin.autodiscover()


urlpatterns = [
    url(r'^', include('zurnatikl.apps.content.urls')),
    # TODO: eventually, move about/credit page templates into content
    url(r'^about/$', TemplateView.as_view(template_name="about.html"),
        name='about'),
    url(r'^credits/$', TemplateView.as_view(template_name="credits.html"),
        name='credits'),
    url(r'^legal/$', TemplateView.as_view(template_name="legal.html"),
        name='legal'),
    url(r'^network/', include('zurnatikl.apps.network.urls',
        namespace='network')),
    url(r'^journals/', include('zurnatikl.apps.journals.urls',
        namespace='journals')),
    url(r'^people/', include('zurnatikl.apps.people.urls',
        namespace='people')),
    url(r'^admin/lookups/', include(ajax_select_urls)),
    url(r'^admin/', include(admin.site.urls) ),

    # add redirect for favicon at root of site
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/images/favicon.ico', permanent=True)),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

zurnatikl/apps/people/forms.py
from django import forms
from ajax_select import make_ajax_field

from zurnatikl.apps.geo.lookups import LocationLookup
from zurnatikl.apps.people.models import Person, School


class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = '__all__'
        # NOTE: schools configured to use horizontal filter in admin

    # ajax autocomplete for locations
    dwellings  = make_ajax_field(Person, 'dwellings', 'location',
        help_text=LocationLookup.help_text)

class SchoolForm(forms.ModelForm):
    class Meta:
        model = School
        fields = '__all__'

    locations  = make_ajax_field(School, 'locations', 'location',
        help_text=LocationLookup.help_text)

zurnatikl/apps/people/views.py
import logging
from django.db.models import Count
from django.views.generic import ListView, DetailView
from django.views.generic.detail import SingleObjectMixin
from django.http import Http404

from .models import Person
from zurnatikl.apps.journals.models import Journal
from zurnatikl.apps.network.base_views import SigmajsJSONView, \
   NetworkGraphExportView, CsvView
from zurnatikl.apps.network.utils import egograph


logger = logging.getLogger(__name__)


class PeopleList(ListView):
    '''List all
    :class:`~zurnatikl.apps.people.models.Person` who have edited
    at least one :class:`~zurnatikl.apps.journals.models.Issue',
    authored one :class:`~zurnatikl.apps.journals.models.Item`,
    or translated one :class:`~zurnatikl.apps.journals.models.Item`.
    Queryset is annotated with counts for the number of items created,
    items translated, and issues edited so that the totals can
    be displayed.
    '''
    model = Person

    queryset = Person.objects.journal_contributors_with_counts() \
                     .prefetch_related('name_set')


class PersonDetail(DetailView):
    '''Display details for a single
    :class:`~zurnatikl.apps.people.models.Person`'''
    model = Person
    # NOTE: could override get_object to 404 for non-editor/non-authors

    def get_queryset(self):
        '''Extend default queryset to add prefetching, so that details for
        items authored and issues edited can be displayed more efficiently.
        '''
        qs = super(PersonDetail, self).get_queryset()
        return qs.prefetch_related(
            'items_created', 'items_created__issue',
            'items_created__issue__editors',
            'items_created__issue__journal', 'items_created__creatorname_set',
            'items_created__creatorname_set__person',
            'items_created__translators',
            'issues_edited', 'issues_edited__journal',
            'issues_edited__editors'
        )


class Egograph(DetailView):
    '''Display an egograph for a single
    :class:`~zurnatikl.apps.people.models.Person`.'''
    # template for displaying / managing javascript egograph
    # actual egograph generated via json view below
    model = Person
    template_name = 'people/person_egograph.html'


class EgographBaseView(SingleObjectMixin):
    '''Base view for generating an egograph for a single person,
    for use in disseminating the graph as JSON, GEXF, or GraphML.'''
    model = Person

    def get_context_data(self, **kwargs):
        person = self.get_object()

        # get the full journal-author-editor network
        graph = Journal.contributor_network()
        # restrict graph to an egograph around the current person
        # with a radius of 1 before export
        try:
            node = graph.vs.find(name=person.network_id)
            return egograph(graph, node)
        except ValueError:
            raise Http404('Vertex does not exist.')


class EgographJSON(SigmajsJSONView, EgographBaseView):
    '''Egograph for a single :class:`~zurnatikl.apps.people.models.Person`
    in a JSON format appropriate for use with Sigma.js'''
    pass


class EgographExport(NetworkGraphExportView, EgographBaseView):
    '''Downloadable eggograph for a single
    :class:`~zurnatikl.apps.people.models.Person` in GEXF or GraphML.'''

    def get_context_data(self, **kwargs):
        # set person slug as base filename
        self.filename = kwargs['slug']
        # inherit egograph generation from EgographBaseView
        return super(EgographExport, self).get_context_data(**kwargs)


class PeopleCSV(CsvView):
    '''Export journal contributor person data as CSV'''
    filename = 'people'
    header_row = ['Last Name', 'First Name', 'Race',
                  'Racial self-description', 'Gender',
                  'Associated Schools', 'URI', 'Dwellings', 'Notes',
                  'Site URL']

    def get_context_data(self, **kwargs):
        people = Person.objects.journal_contributors() \
                       .prefetch_related('schools', 'dwellings')
        for person in people:
            yield [
                person.last_name, person.first_name,
                ', '.join(person.race or []),
                person.racial_self_description,
                person.gender,
                ', '.join(sch.name for sch in person.schools.all()),
                person.uri,
                u'; '.join(unicode(loc) for loc in person.dwellings.all()),
                # remove line breaks from notes to avoid generating broken CSV
                person.notes.replace('\n', ' ').replace('\r', ' '),
                self.request.build_absolute_uri(person.get_absolute_url())
            ]

zurnatikl/apps/people/templates/people/person_detail.html
{% extends 'site_base.html' %}
{# display details for a single person #}
{% load journal_extras %}

{% block page-subtitle %} | People | {{ person.firstname_lastname }}{% endblock %}

{% block breadcrumb-links %}
  <li><a href="{% url 'people:list' %}">People</a></li>
  <li class="active">{{ person.firstname_lastname }}</li>
{% endblock %}

{% block content %}
{# todo: page content? #}
<section class="row">
    <div class="col-lg-12">
        <div class="content">

<div class="top-bar">
    <h1>{{ person.firstname_lastname }}</h1>
    <a class="btn btn-secondary btn-connect" href="{% url 'people:egograph' person.slug %}">View Connections</a>
</div>

{# display alternate names, if any #}
{% if person.name_set.all.count %}
<div class="alternate">
    {{ person.name_set.all|join:', ' }}
</div>
{% endif %}

{% comment %}  jump links disabled for now, based on resonance design
{# only display nav if at least two sections are present #}
{% if person.items_created.all.exists and person.issues_edited.all.exists or person.items_created.all.exists and person.items_translated.all.exists or person.items_translated.all.exists and person.issues_edited.all.exists %}
<div>
    <ul>
        {% if person.items_created.all.exists %}
        <li><a href="#author">Author</a></li>
        {% endif %}
        {% if person.issues_edited.all.exists %}
        <li><a href="#editor">Editor</a></li>
        {% endif %}
        {% if person.items_translated.all.exists %}
        <li><a href="#translator">Translator</a></li>
        {% endif %}
    <ul>
</div>
{% endif %}
{% endcomment %}

{% if person.items_created.all.exists %}

<h2 class="author count">As Author<span class="author">{{ person.items_created.all|length }}</span></h2>

{# group by journal then by issue for nested list of items by journal/issue #}
{% regroup person.items_created.all by issue.journal as items_by_journal %}
{% for item_group in items_by_journal %}
    {% with journal=item_group.grouper %}
    <h3><a href="{% url 'journals:journal' journal.slug %}">{{ journal }}</a></h3>
        <dl>
        {% regroup item_group.list by issue as items_by_issue %}
        {% for issue_items in items_by_issue %}
            {% with issue=issue_items.grouper %}
            <dt>{% include 'journals/snippets/issue_link.html' %}</dt>

                {% for item in issue_items.list %}
                <dd>
                {{ item }}{% if item.translators.all %}, trans.
                {% for translator in item.translators.all %}
                <a href="{{translator.get_absolute_url}}">{{translator}}</a>{% if item.translators.all.count == 1 %}{% elif forloop.counter == item.translators.all.count %}{% else %},{% endif %}
                {% endfor %}
                {% endif %}
                {# display person's name used for this piece if set #}
                {% for cn in item.creatorname_set.all %}
                    {% if cn.person == person and cn.name_used %}
                    <i>(as {{ cn.name_used }})</i>
                    {% endif %}
                {% endfor %}
                {# display co-authors if any #}
                {% if item.creatorname_set.count > 1 %}
                    <p class="co-authors">With
                    {% for cn in item.creatorname_set.all %}
                        {% if cn.person != person %} {# don't display current person #}
                            <span class="name"><a href="{{ cn.person.get_absolute_url }}">
                                {{ cn.person.firstname_lastname }}</a>{% if cn.name %} (as {{ cn.name }}){% endif %}</span>
                        {% endif %}
                    {% endfor %}
                    </p>
                {% endif %}
            </dd>
            {% endfor %}
            {% endwith %} {# end issue group #}
        {% endfor %}
    </dl> {# end journal group #}
    {% endwith %}
{% endfor %}
{% endif %}

{% if person.issues_edited.all.exists %}

<h2 class="editor count">As Editor<span class="editor">{{ person.issues_edited.all|length }}</span></h2>
{# group issues by journal to generate nested list #}
{% regroup person.issues_edited.all by journal as issues_by_journal %}

{% for issue_group in issues_by_journal %}
    {% with journal=issue_group.grouper %}
    <h3><a href="{% url 'journals:journal' journal.slug %}">{{ journal }}</a></h3>
    <dl>
        {% for issue in issue_group.list %}
          <dt>{% include 'journals/snippets/issue_link.html' with ed_with=person %}</dt>
        {% endfor %}
    </dl>
    {% endwith %}
{% endfor %}

{% endif %}

{% if person.items_translated.all.exists %} {# NOTE: basically the same as author #}
<h2 class="translate count">As Translator<span class="translate">{{ person.items_translated.all|length }}</span></h2>
{# group by journal then by issue for nested list of items by journal/issue #}
{% regroup person.items_translated.all by issue.journal as items_by_journal %}

{% for item_group in items_by_journal %}
    {% with journal=item_group.grouper %}
    <h3><a href="{% url 'journals:journal' journal.slug %}">{{ journal }}</a></h3>
        <dl>
        {% regroup item_group.list by issue as items_by_issue %}
        {% for issue_items in items_by_issue %}
            {% with issue=issue_items.grouper %}
            <dt>{% include 'journals/snippets/issue_link.html' %}</dt>
                {% for item in issue_items.list %}
                <dd>{{ item }}{% if item.creators.all %}, by
                    {% for creator in item.creators.all %}
                    <a href="{{creator.get_absolute_url}}">{{creator.firstname_lastname}}</a>{% if item.creators.all.count == 1 %}{% elif forloop.counter == item.creators.all.count %}{% else %},{% endif %}
                    {% endfor %}
                {% endif %}
                </dd>
                {% endfor %}
            {% endwith %} {# end issue group #}
        {% endfor %}
    </dl>{# end journal group #}
    {% endwith %}
{% endfor %}

{% endif %}

</div>
</div>
</section>
{% endblock %}

zurnatikl/apps/people/templates/people/person_egograph.html
{% extends 'network/graph_base.html' %}
{% load static %}
{# display an egograph for a single journal contributor #}

{% block page-subtitle %} | People | {{ person.firstname_lastname }} | Egograph{% endblock %}

{% block breadcrumb-links %}
  <li><a href="{% url 'people:list' %}">People</a></li>
  <li><a href="{% url 'people:person' person.slug %}">{{ person.firstname_lastname }}</a></li>
  <li class="active">Egograph</li>
{% endblock %}

{% block download-graph %}
    {% url 'people:egograph-export' person.slug 'graphml' as graphml_url %}
    {% url 'people:egograph-export' person.slug 'gml' as gml_url %}
    {% include 'network/snippets/download_graph.html' %}
{% endblock %}

{% block pregraph-content %}


<h1>{{ person.firstname_lastname }}'s Connections</h1>

{% endblock %}

{% block graph-init %}
<script>
var s = init_sigma_graph({
  json_url: "{% url 'people:egograph-json' person.slug %}",
  sigma: {
    labelThreshold: 6,
    edgeLabelThreshold: 1
  }
});
</script>
{% endblock %}

zurnatikl/apps/people/templates/people/person_list.html
{% extends 'site_base.html' %}
{# list journal contributors (authors, editors, translators) #}
{% load static %}

{% block page-subtitle %} | Journal Contributors {% endblock %}

{% block breadcrumb-links %}
  <li><a href="{% url 'people:list' %}" class="active">Journal Contributors</a></li>
{% endblock %}

{% block content %}
{# TODO: use page_base ? #}
<section class="row">
{# NOTE: saundra says the column class can be removed; should be removed everywhere but text content pages, as it adds unnecessary padding elsewhere #}
    <div class="col-sm-12">  {# why col-sm-12 vs col-lg-12 in content pages? #}
        <div class="content">
            <h1>Journal Contributors</h1>
            <p class="lead">Track {{ object_list.count }} people as authors, editors, and translators.</p>

            <div id="authors">
                <div class="col-sm-8 filter-list">
            {# FIXME: eultheme filter class is interfering with styles here #}
                    <a class="filter" data="all">All</a>
                    <a class="filter" data="author">Author</a>
                    <a class="filter" data="editor">Editor</a>
                    <a class="filter" data="translate">Translator</a>
                </div>
                <div class="input-group col-md-4">
                    <input type="text" class="search" placeholder="Search People" />
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="button">
                            <i class="glyphicon glyphicon-search"></i>
                        </button>
                    </span>

                </div>

                <ul class="list col-sm-12">
                {% for person in object_list %}
                <li class="col-lg-3 col-md-4 col-sm-6">
                    <a class="tile" href="{% url 'people:person' person.slug %}">
                        <div class="count">
                            {% if person.num_created %}
                                <div class="author">{{ person.num_created }}</div>
                            {% endif %}
                            {% if person.num_edited %}
                                <div class="editor">{{ person.num_edited }}</div>
                            {% endif %}
                            {% if person.num_translated %}
                                <div class="translate">{{ person.num_translated }}</div>
                            {% endif %}
                        </div>

                        <div class="title">{{ person }}</div>
                        {# display alternate names, if any #}
                        {% if person.name_set.all.count %}
                        <div class="alternate">{{ person.name_set.all|join:', ' }}</div>
                        {% endif %}
                    </a>
                </li>
                {% endfor %}

            </div>

        </div>
    </div>
</section>

{% endblock %}

{% block javascript %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/list.js/1.2.0/list.min.js"></script>
    <script src="{% static 'js/jquery.matchHeight-min.js' %}"></script>
    <script src="{% static 'js/people.js' %}"></script>
{% endblock %}